import 'package:dierb_api_client/dierb_api_client.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class MenusUploadScreen extends StatefulWidget{const MenusUploadScreen({super.key});@override State<MenusUploadScreen>createState()=>_State();}
class _State extends State<MenusUploadScreen>{final api=DierbApi();Map<String,dynamic>?store;bool loading=true;String?error;@override void initState(){super.initState();_load();}@override void dispose(){api.close();super.dispose();}Future<void>_load()async{try{final r=await api.merchantStore();if(mounted)setState((){store=r['store']is Map?Map<String,dynamic>.from(r['store']as Map):null;loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error=e is DierbApiException?e.message:'تعذر تحميل المنتجات';});}}Future<void>_editor([Map<String,dynamic>?p])async{if(store==null)return;await Navigator.push(context,MaterialPageRoute(builder:(_)=>ProductEditor(storeId:store!['id'].toString(),product:p)));await _load();}
@override Widget build(BuildContext context){
  final products=store?['products'] as List? ?? const[];
  Widget body;
  if(loading){body=const Center(child:CircularProgressIndicator());}
  else if(error!=null){body=Center(child:Text(error!));}
  else if(store==null){body=const Center(child:Text('أكمل إعداد المتجر أولاً'));}
  else if(products.isEmpty){body=const Center(child:Text('لسه مفيش منتجات. أضف أول منتج.'));}
  else{body=RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.fromLTRB(14,14,14,90),itemCount:products.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){
    final p=Map<String,dynamic>.from(products[i] as Map),images=p['images'] as List? ?? const[];
    final url=images.isEmpty?'':(images.first as Map)['url'].toString(),price=((p['salePricePiasters']??p['pricePiasters']??0)as num)/100;
    return Card(child:ListTile(leading:_Image(url:url),title:Text((p['name']??'منتج').toString(),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('$price ج.م • ${p['available']==true?'متاح':'موقوف'}'),onTap:()=>_editor(p),trailing:PopupMenuButton<String>(onSelected:(v)async{try{if(v=='delete')await api.archiveProduct(p['id'].toString());else await api.updateProduct(p['id'].toString(),{'available':p['available']!=true});await _load();}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e is DierbApiException?e.message:'تعذر التحديث')));}},itemBuilder:(_)=>[PopupMenuItem(value:'toggle',child:Text(p['available']==true?'إيقاف المنتج':'تفعيل المنتج')),const PopupMenuItem(value:'delete',child:Text('حذف'))])));
  }));}
  return Scaffold(appBar:AppBar(title:const Text('منتجات المتجر',style:TextStyle(fontWeight:FontWeight.w900))),floatingActionButton:store==null?null:FloatingActionButton.extended(onPressed:()=>_editor(),icon:const Icon(Icons.add),label:const Text('إضافة منتج')),body:body);
}}
class ProductEditor extends StatefulWidget{const ProductEditor({super.key,required this.storeId,this.product});final String storeId;final Map<String,dynamic>?product;@override State<ProductEditor>createState()=>_EditorState();}
class _EditorState extends State<ProductEditor>{final api=DierbApi(),picker=ImagePicker(),name=TextEditingController(),description=TextEditingController(),price=TextEditingController(),sale=TextEditingController(),stock=TextEditingController();bool available=true,busy=false,uploading=false;String?image,error;
@override void initState(){super.initState();final p=widget.product;if(p!=null){name.text=(p['name']??'').toString();description.text=(p['description']??'').toString();price.text=(((p['pricePiasters']as num?)??0)/100).toString();if(p['salePricePiasters']!=null)sale.text=(((p['salePricePiasters']as num)/100)).toString();stock.text=(p['stock']??'').toString();available=p['available']==true;final imgs=p['images']as List? ?? const[];if(imgs.isNotEmpty)image=(imgs.first as Map)['url']?.toString();}}
@override void dispose(){api.close();name.dispose();description.dispose();price.dispose();sale.dispose();stock.dispose();super.dispose();}
Future<void>_pick()async{final x=await picker.pickImage(source:ImageSource.gallery,imageQuality:82,maxWidth:1600);if(x==null)return;setState((){uploading=true;error=null;});try{final r=await api.uploadImage(await x.readAsBytes(),x.name);if(mounted)setState(()=>image=r['url'].toString());}catch(e){if(mounted)setState(()=>error=e is DierbApiException?e.message:'تعذر رفع الصورة');}finally{if(mounted)setState(()=>uploading=false);}}
Future<void>_save()async{final amount=double.tryParse(price.text);if(name.text.trim().length<2||amount==null||amount<0){setState(()=>error='اكتب اسم وسعر صحيح');return;}setState((){busy=true;error=null;});final saleAmount=double.tryParse(sale.text);final body=<String,dynamic>{'storeId':widget.storeId,'name':name.text.trim(),'description':description.text.trim(),'pricePiasters':(amount*100).round(),'salePricePiasters':saleAmount==null?null:(saleAmount*100).round(),'stock':int.tryParse(stock.text),'available':available,'imageUrls':image==null?[]:[image]};body.removeWhere((_,v)=>v==null);try{if(widget.product==null)await api.createProduct(body);else await api.updateProduct(widget.product!['id'].toString(),body);if(mounted)Navigator.pop(context);}catch(e){if(mounted)setState(()=>error=e is DierbApiException?e.message:'تعذر حفظ المنتج');}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.product==null?'إضافة منتج':'تعديل المنتج')),body:ListView(padding:const EdgeInsets.all(16),children:[InkWell(onTap:uploading?null:_pick,child:AspectRatio(aspectRatio:16/9,child:Container(clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:const Color(0xFFEAF2ED),borderRadius:BorderRadius.circular(22)),child:uploading?const Center(child:CircularProgressIndicator()):image==null?const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.add_photo_alternate_outlined,size:48),Text('اختيار صورة المنتج')]):Image.network(image!,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.broken_image_outlined,size:48))))),const SizedBox(height:16),TextField(controller:name,decoration:const InputDecoration(labelText:'اسم المنتج')),const SizedBox(height:10),TextField(controller:description,maxLines:3,decoration:const InputDecoration(labelText:'الوصف')),const SizedBox(height:10),Row(children:[Expanded(child:TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'السعر بالجنيه'))),const SizedBox(width:10),Expanded(child:TextField(controller:sale,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'سعر العرض')))]),const SizedBox(height:10),TextField(controller:stock,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المخزون (اختياري)')),SwitchListTile(value:available,onChanged:(v)=>setState(()=>available=v),title:const Text('متاح للعملاء')),if(error!=null)Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)),const SizedBox(height:16),FilledButton.icon(onPressed:busy||uploading?null:_save,icon:busy?const SizedBox.square(dimension:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save_outlined),label:const Text('حفظ المنتج'))]));}
class _Image extends StatelessWidget{const _Image({required this.url});final String url;@override Widget build(BuildContext context)=>ClipRRect(borderRadius:BorderRadius.circular(10),child:url.isEmpty?const SizedBox(width:56,height:56,child:Icon(Icons.image_outlined)):Image.network(url,width:56,height:56,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox(width:56,height:56,child:Icon(Icons.broken_image_outlined))));}
