import 'package:dierb_api_client/dierb_api_client.dart';
import 'package:flutter/material.dart';
import '../authentication/auth_screen.dart';
import '../design/dierb_theme.dart';
import 'earning_screens.dart';
import 'history_screen.dart';
import 'new_orders_screen.dart';
import 'store_settings_screen.dart';
import '../uploadScreens.dart/menus_upload_screen.dart';
import '../notifications/notification_center_page.dart';

class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen>createState()=>_State();}
class _State extends State<HomeScreen>{final api=DierbApi();Map<String,dynamic>?response;List<dynamic>orders=const[];bool loading=true;String?error;
@override void initState(){super.initState();_load();}@override void dispose(){api.close();super.dispose();}
Future<void>_load()async{try{final values=await Future.wait([api.merchantStore(),api.orders()]);if(mounted)setState((){response=Map<String,dynamic>.from(values[0]as Map);orders=values[1]as List;loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error=e is DierbApiException?e.message:'تعذر تحميل لوحة التاجر';});}}
Future<void>_logout()async{await api.logout();if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AuthScreen()),(_)=>false);}void _open(Widget page)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>page)).then((_)=>_load());
@override Widget build(BuildContext context){final merchant=response?['merchant']is Map?Map<String,dynamic>.from(response!['merchant']as Map):const<String,dynamic>{},store=response?['store']is Map?Map<String,dynamic>.from(response!['store']as Map):null;final fresh=orders.where((x)=>(x as Map)['status']=='waitingMerchantApproval').length,current=orders.where((x)=>!['delivered','rejected','cancelled'].contains((x as Map)['status'])).length;
return Scaffold(appBar:AppBar(title:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('ديرب للتجار',style:TextStyle(fontWeight:FontWeight.w900)),Text('إدارة متجرك وطلباتك',style:TextStyle(fontSize:12,color:DierbTheme.muted))]),actions:[IconButton(onPressed:()=>_open(const NotificationCenterPage()),icon:const Icon(Icons.notifications_none_rounded)),IconButton(onPressed:_logout,icon:const Icon(Icons.logout_rounded))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!),TextButton(onPressed:_load,child:const Text('حاول تاني'))])):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[
if(store==null)Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('جهّز ملف متجرك',style:TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:8),Text('حالة حساب التاجر: ${merchant['status']??'pending'}'),const SizedBox(height:12),FilledButton(onPressed:()=>_open(const StoreSettingsScreen()),child:const Text('إعداد المتجر'))])))else _Store(store:store,onToggle:(v)async{try{await api.setStoreOpen(store['id'].toString(),v);await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e is DierbApiException?e.message:'تعذر التحديث')));}},settings:()=>_open(const StoreSettingsScreen())),
const SizedBox(height:16),Row(children:[Expanded(child:_Metric(title:'طلبات جديدة',count:fresh,icon:Icons.notifications_active_outlined,color:const Color(0xFFFFF3E6))),const SizedBox(width:10),Expanded(child:_Metric(title:'طلبات حالية',count:current,icon:Icons.delivery_dining_rounded,color:const Color(0xFFEAF1F8)))]),const SizedBox(height:22),const Text('إدارة المتجر',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:12),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:3,childAspectRatio:.92,crossAxisSpacing:10,mainAxisSpacing:10,children:[_Action(Icons.receipt_long_rounded,'الطلبات',()=>_open(const NewOrdersScreen())),_Action(Icons.inventory_2_rounded,'المنتجات',()=>_open(const MenusUploadScreen())),_Action(Icons.add_box_rounded,'إضافة منتج',()=>_open(const MenusUploadScreen())),_Action(Icons.storefront_rounded,'ملف المتجر',()=>_open(const StoreSettingsScreen())),_Action(Icons.bar_chart_rounded,'المبيعات',()=>_open(const HistoryScreen())),_Action(Icons.account_balance_wallet_rounded,'الأرباح',()=>_open(const EarningScreen()))])])));}}
class _Store extends StatelessWidget{const _Store({required this.store,required this.onToggle,required this.settings});final Map<String,dynamic>store;final ValueChanged<bool>onToggle;final VoidCallback settings;@override Widget build(BuildContext context){final approved=store['status']=='approved';return Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Row(children:[CircleAvatar(radius:28,backgroundImage:(store['logoUrl']??'').toString().isEmpty?null:NetworkImage(store['logoUrl']),child:(store['logoUrl']??'').toString().isEmpty?const Icon(Icons.store):null),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((store['name']??'متجرك').toString(),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),Text(approved?'متجر معتمد':'قيد مراجعة الإدارة')])),Switch(value:store['isOpen']==true,onChanged:approved?onToggle:null)]),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:settings,icon:const Icon(Icons.edit_outlined),label:const Text('تعديل ملف المتجر')))])));}}
class _Metric extends StatelessWidget{const _Metric({required this.title,required this.count,required this.icon,required this.color});final String title;final int count;final IconData icon;final Color color;@override Widget build(BuildContext context)=>Container(height:105,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:color,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:DierbTheme.primary),const Spacer(),Text('$count',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),Text(title)]));}
class _Action extends StatelessWidget{const _Action(this.icon,this.label,this.tap);final IconData icon;final String label;final VoidCallback tap;@override Widget build(BuildContext context)=>Card(child:InkWell(onTap:tap,borderRadius:BorderRadius.circular(16),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:DierbTheme.primary,size:30),const SizedBox(height:8),Text(label,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w800))])));}
