import 'dart:async';
import 'package:dierb_api_client/dierb_api_client.dart';
import 'package:dierb_core/dierb_core.dart';
import 'package:flutter/material.dart';
import '../orders/order_conversation_page.dart';

class NewOrdersScreen extends StatefulWidget { const NewOrdersScreen({super.key}); @override State<NewOrdersScreen> createState()=>_NewOrdersScreenState(); }
class _NewOrdersScreenState extends State<NewOrdersScreen>{
  final api=DierbApi();List<dynamic> orders=const[];bool loading=true;String? error;Timer? timer;
  @override void initState(){super.initState();_load();timer=Timer.periodic(const Duration(seconds:8),(_)=>_load(silent:true));}
  @override void dispose(){timer?.cancel();api.close();super.dispose();}
  Future<void> _load({bool silent=false})async{try{final v=await api.orders();if(mounted)setState((){orders=v;loading=false;error=null;});}catch(e){if(mounted&&!silent)setState((){loading=false;error=e is DierbApiException?e.message:'تعذر تحميل الطلبات';});}}
  Future<void> _status(String id,String status)async{try{await api.transition(id,status);await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تحديث الطلب')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e is DierbApiException?e.message:'تعذر تحديث الطلب')));}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('طلبات المتجر',style:TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!),TextButton(onPressed:_load,child:const Text('حاول تاني'))])):orders.isEmpty?const Center(child:Text('لا توجد طلبات حتى الآن')):RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.all(14),itemCount:orders.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_OrderCard(data:Map<String,dynamic>.from(orders[i] as Map),status:_status))));
}
class _OrderCard extends StatelessWidget{
  const _OrderCard({required this.data,required this.status});final Map<String,dynamic> data;final Future<void> Function(String,String) status;
  @override Widget build(BuildContext context){final id=data['id'].toString(),state=OrderStatusCodec.fromStorage(data['status']),items=data['items'] as List? ?? const[],total=((data['totalPiasters'] as num?)?.toInt()??0)/100;final address=data['addressSnapshot'] is Map?Map<String,dynamic>.from(data['addressSnapshot'] as Map):const<String,dynamic>{};
    Widget action=const SizedBox.shrink();if(state==OrderStatus.waitingMerchantApproval)action=Row(children:[Expanded(child:OutlinedButton(onPressed:()=>status(id,'rejected'),child:const Text('رفض'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:()=>status(id,'acceptedByMerchant'),child:const Text('قبول')))]);else if(state==OrderStatus.acceptedByMerchant)action=FilledButton(onPressed:()=>status(id,'preparing'),child:const Text('بدء التجهيز'));else if(state==OrderStatus.preparing)action=FilledButton(onPressed:()=>status(id,'readyForPickup'),child:const Text('جاهز للمندوب'));
    return Card(color:state==OrderStatus.waitingMerchantApproval?const Color(0xFFFFFBF2):null,child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[CircleAvatar(child:Icon(state==OrderStatus.waitingMerchantApproval?Icons.notifications_active:Icons.receipt_long)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(state.labelAr,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),Text('#${id.substring(0,id.length>7?7:id.length)}')])),Text('${total.toStringAsFixed(0)} ج.م',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))]),const Divider(height:24),...items.map((raw){final x=Map<String,dynamic>.from(raw as Map);return ListTile(contentPadding:EdgeInsets.zero,leading:_Thumb(url:(x['imageUrl']??'').toString()),title:Text('${x['name']??'منتج'} × ${x['quantity']??1}'),trailing:Text('${(((x['unitPricePiasters']as num?)?.toInt()??0)*(x['quantity']as num? ??1))/100} ج.م'));}),if(address.isNotEmpty)Text('${address['recipientName']??''}\n${address['phone']??''}\n${address['addressLine']??''}'),const SizedBox(height:10),OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderConversationPage(orderId:id))),icon:const Icon(Icons.forum_outlined),label:const Text('محادثة الطلب')),const SizedBox(height:8),action])));
  }
}
class _Thumb extends StatelessWidget{const _Thumb({required this.url});final String url;@override Widget build(BuildContext context)=>Container(width:48,height:48,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:const Color(0xFFEAF2ED),borderRadius:BorderRadius.circular(12)),child:url.isEmpty?const Icon(Icons.inventory_2_outlined):Image.network(url,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.broken_image_outlined)));}
