import'dart:async';import'package:dierb_api_client/dierb_api_client.dart';import'package:dierb_core/dierb_core.dart';import'package:flutter/material.dart';import'../orders/order_conversation_page.dart';
enum RiderOrdersMode{available,pickup,delivering,history}extension RiderMode on RiderOrdersMode{String get title=>const{RiderOrdersMode.available:'طلبات توصيل متاحة',RiderOrdersMode.pickup:'طلبات استلمتها',RiderOrdersMode.delivering:'في الطريق للعميل',RiderOrdersMode.history:'سجل التوصيل'}[this]!;}
class RiderOrdersPage extends StatefulWidget{const RiderOrdersPage({super.key,required this.mode});final RiderOrdersMode mode;@override State<RiderOrdersPage>createState()=>_State();}
class _State extends State<RiderOrdersPage>{final api=DierbApi();List<dynamic>orders=const[];bool loading=true;String?error;Timer?timer;
@override void initState(){super.initState();load();timer=Timer.periodic(const Duration(seconds:8),(_)=>load(silent:true));}@override void dispose(){timer?.cancel();api.close();super.dispose();}
Future<void>load({bool silent=false})async{try{final v=widget.mode==RiderOrdersMode.available?await api.availableOrders():await api.orders();if(mounted)setState((){orders=v.where((x){final s=(x as Map)['status'];return widget.mode==RiderOrdersMode.available||widget.mode==RiderOrdersMode.pickup&&s=='pickedUpByRider'||widget.mode==RiderOrdersMode.delivering&&['onTheWay','arrived'].contains(s)||widget.mode==RiderOrdersMode.history&&s=='delivered';}).toList();loading=false;error=null;});}catch(e){if(mounted&&!silent)setState((){loading=false;error=e is DierbApiException?e.message:'تعذر تحميل الطلبات';});}}
Future<void>act(String id,String action)async{try{if(action=='claim')await api.claimOrder(id);else await api.transition(id,action);await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e is DierbApiException?e.message:'تعذر تحديث الطلب')));}}
@override Widget build(BuildContext context){Widget body;if(loading){body=const Center(child:CircularProgressIndicator());}else if(error!=null){body=Center(child:Text(error!));}else if(orders.isEmpty){body=const Center(child:Text('لا توجد طلبات في هذه القائمة'));}else{body=RefreshIndicator(onRefresh:load,child:ListView.separated(padding:const EdgeInsets.all(14),itemCount:orders.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>Card(child:_card(Map<String,dynamic>.from(orders[i]as Map)))));}return Scaffold(appBar:AppBar(title:Text(widget.mode.title)),body:body);}
Widget _card(Map<String,dynamic>d){final id=d['id'].toString(),items=d['items']as List? ?? const[],store=d['store']is Map?Map<String,dynamic>.from(d['store']as Map):const<String,dynamic>{},address=d['deliveryAddress']is Map?Map<String,dynamic>.from(d['deliveryAddress']as Map):const<String,dynamic>{},state=OrderStatusCodec.fromStorage(d['status']);String?next,label;if(widget.mode==RiderOrdersMode.available){next='claim';label='استلام الطلب';}else if(state==OrderStatus.pickedUpByRider){next='onTheWay';label='خرجت للتوصيل';}else if(state==OrderStatus.onTheWay){next='arrived';label='وصلت للعميل';}else if(state==OrderStatus.arrived){next='delivered';label='تم التسليم';}return Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text((store['name']??'متجر ديرب').toString(),style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900)),Text(state.labelAr,style:const TextStyle(color:Color(0xFF166534),fontWeight:FontWeight.w800)),const Divider(),Text('الاستلام: ${store['address']??''}'),const SizedBox(height:6),Text('التوصيل: ${address['recipientName']??''} — ${address['phone']??''}\n${address['addressLine']??''}'),if(items.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text(items.map((x)=>'${(x as Map)['quantity']} × ${x['name']}').join(' • '))),if(widget.mode!=RiderOrdersMode.available)OutlinedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderConversationPage(orderId:id))),icon:const Icon(Icons.forum_outlined),label:const Text('محادثة الطلب')),if(next!=null)FilledButton(onPressed:()=>act(id,next!),child:Text(label!))]));}}
