import{ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';import{OrderStatus,Prisma,Role}from'@prisma/client';import{PrismaService}from'../prisma/prisma.service';import{NotificationsService}from'../notifications/notifications.service';import{CreateOrderDto}from'./dto';import{assertTransition}from'./order-state-machine';
@Injectable()export class OrdersService{
 constructor(private readonly prisma:PrismaService,private readonly notifications:NotificationsService){}
 async create(customerId:string,dto:CreateOrderDto){
  const store=await this.prisma.store.findFirst({where:{id:dto.storeId,status:'approved',isOpen:true,deletedAt:null},include:{merchant:true}});if(!store)throw new NotFoundException('Store unavailable');
  const products=await this.prisma.product.findMany({where:{id:{in:dto.items.map(i=>i.productId)},storeId:store.id,available:true,deletedAt:null},include:{images:{orderBy:{sortOrder:'asc'},take:1}}});if(products.length!==new Set(dto.items.map(i=>i.productId)).size)throw new NotFoundException('Product unavailable');
  const lines=dto.items.map(line=>{const p=products.find(x=>x.id===line.productId)!;const unit=p.salePricePiasters??p.pricePiasters;return{productId:p.id,name:p.name,imageUrl:p.images[0]?.url,unitPricePiasters:unit,quantity:line.quantity};});
  const subtotal=lines.reduce((sum,line)=>sum+line.unitPricePiasters*line.quantity,0);const total=subtotal+store.deliveryFeePiasters;
  const order=await this.prisma.$transaction(async tx=>{const created=await tx.order.create({data:{customerId,storeId:store.id,status:OrderStatus.waitingMerchantApproval,subtotalPiasters:subtotal,deliveryFeePiasters:store.deliveryFeePiasters,discountPiasters:0,totalPiasters:total,customerName:dto.customerName,customerPhone:dto.customerPhone,deliveryAddress:dto.deliveryAddress as Prisma.InputJsonValue,notes:dto.notes,items:{create:lines},history:{create:{toStatus:OrderStatus.waitingMerchantApproval,actorId:customerId,actorRole:Role.customer}}},include:{items:true,history:true}});return created;});
  await this.notifications.create(store.merchant.userId,'طلب جديد','وصلك طلب جديد من عميل ديرب','new_order',order.id);return order;
 }
 list(userId:string,role:Role){const where=role===Role.customer?{customerId:userId}:role===Role.rider?{rider:{userId}}:{store:{merchant:{userId}}};return this.prisma.order.findMany({where,include:{items:true,history:{orderBy:{createdAt:'asc'}},store:true},orderBy:{createdAt:'desc'},take:100});}
 async available(riderUserId:string){const rider=await this.prisma.rider.findUnique({where:{userId:riderUserId}});if(!rider||rider.status!=='approved'||!rider.available)throw new ForbiddenException();return this.prisma.order.findMany({where:{status:OrderStatus.readyForPickup,riderId:null},include:{items:true,store:true},take:50,orderBy:{createdAt:'asc'}});}
 async claim(orderId:string,riderUserId:string){const rider=await this.prisma.rider.findUnique({where:{userId:riderUserId}});if(!rider||rider.status!=='approved'||!rider.available)throw new ForbiddenException();return this.prisma.$transaction(async tx=>{const changed=await tx.order.updateMany({where:{id:orderId,status:OrderStatus.readyForPickup,riderId:null},data:{riderId:rider.id,status:OrderStatus.pickedUpByRider,claimedAt:new Date()}});if(changed.count!==1)throw new ForbiddenException('Order already claimed');await tx.orderStatusHistory.create({data:{orderId,fromStatus:OrderStatus.readyForPickup,toStatus:OrderStatus.pickedUpByRider,actorId:riderUserId,actorRole:Role.rider}});await tx.riderJob.create({data:{orderId,riderId:rider.id,status:'active',acceptedAt:new Date()}});const order=await tx.order.findUniqueOrThrow({where:{id:orderId},include:{store:{include:{merchant:true}}}});await this.notifications.create(order.customerId,'المندوب استلم طلبك','طلبك في طريقه إليك','rider_claimed',order.id);return order;});}
 async transition(orderId:string,userId:string,role:Role,to:OrderStatus,note?:string){const order=await this.prisma.order.findUnique({where:{id:orderId},include:{store:{include:{merchant:true}},rider:true}});if(!order)throw new NotFoundException();const allowed=role===Role.customer?order.customerId===userId:role===Role.rider?order.rider?.userId===userId:order.store.merchant.userId===userId;if(!allowed&&!['admin','super_admin'].includes(role))throw new ForbiddenException();if(!['admin','super_admin'].includes(role))assertTransition(order.status,to,role);const actorRole=role;const updated=await this.prisma.$transaction(async tx=>{const changed=await tx.order.updateMany({where:{id:orderId,status:order.status},data:{status:to,...(to===OrderStatus.delivered&&{deliveredAt:new Date()}),...([OrderStatus.cancelled,OrderStatus.rejected].includes(to)&&{cancelledAt:new Date()})}});if(changed.count!==1)throw new ForbiddenException('Order changed concurrently');await tx.orderStatusHistory.create({data:{orderId,fromStatus:order.status,toStatus:to,actorId:userId,actorRole,note}});if(to===OrderStatus.delivered&&order.riderId)await tx.riderJob.updateMany({where:{orderId,riderId:order.riderId},data:{status:'completed',completedAt:new Date()}});return tx.order.findUniqueOrThrow({where:{id:orderId},include:{items:true,history:true}});});
  const labels:Partial<Record<OrderStatus,string>>={acceptedByMerchant:'تم قبول طلبك',preparing:'طلبك جاري التجهيز',readyForPickup:'طلبك جاهز للمندوب',onTheWay:'طلبك في الطريق',arrived:'المندوب وصل',delivered:'تم تسليم الطلب',rejected:'المتجر اعتذر عن الطلب'};if(labels[to])await this.notifications.create(order.customerId,labels[to]!,labels[to]!,'order_status',order.id);return updated;}
}
